// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS8WCylnTc639O8Ufyo3RqMy-L2DIWxcc',
    appId: '1:630839774463:android:be4f718f4e4425f5bc10ca',
    messagingSenderId: '630839774463',
    projectId: 'tripx-91358',
    storageBucket: 'tripx-91358.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRhZHTlBZ6rogn1Hrc56j7iLCb0O6EySY',
    appId: '1:630839774463:ios:966af88e830ad858bc10ca',
    messagingSenderId: '630839774463',
    projectId: 'tripx-91358',
    storageBucket: 'tripx-91358.firebasestorage.app',
    iosClientId: '630839774463-epd6923rlqc3igqc5h7ekje0ceggrcue.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripx',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdUL8Jeeesn-4jTnzisov03670D83iuoM',
    appId: '1:630839774463:web:e50d945a6f19aeb3bc10ca',
    messagingSenderId: '630839774463',
    projectId: 'tripx-91358',
    authDomain: 'tripx-91358.firebaseapp.com',
    storageBucket: 'tripx-91358.firebasestorage.app',
    measurementId: 'G-0YXQW9GM5Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRhZHTlBZ6rogn1Hrc56j7iLCb0O6EySY',
    appId: '1:630839774463:ios:966af88e830ad858bc10ca',
    messagingSenderId: '630839774463',
    projectId: 'tripx-91358',
    storageBucket: 'tripx-91358.firebasestorage.app',
    iosClientId: '630839774463-epd6923rlqc3igqc5h7ekje0ceggrcue.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdUL8Jeeesn-4jTnzisov03670D83iuoM',
    appId: '1:630839774463:web:f3221a490cdb3ebdbc10ca',
    messagingSenderId: '630839774463',
    projectId: 'tripx-91358',
    authDomain: 'tripx-91358.firebaseapp.com',
    storageBucket: 'tripx-91358.firebasestorage.app',
    measurementId: 'G-PZQE93KSFC',
  );

}